-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 10:11:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vzm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vzm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vzm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vzm` ;

-- -----------------------------------------------------
-- Table `vzm`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vzm`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vzm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vzm`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(40) NOT NULL,
  `last_name` VARCHAR(40) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `user_password` VARCHAR(250) NOT NULL,
  `user_level` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_unique` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vzm`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vzm`.`topics` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `topic_name` VARCHAR(255) NOT NULL,
  `topic_date` DATETIME NOT NULL,
  `topic_author` INT NOT NULL,
  `topic_category` INT NOT NULL,
  `topic_content` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_id`),
  INDEX `topic_category` (`topic_category` ASC) VISIBLE,
  INDEX `topic_author` (`topic_author` ASC) VISIBLE,
  CONSTRAINT `topics_ibfk_1`
    FOREIGN KEY (`topic_category`)
    REFERENCES `vzm`.`categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `topics_ibfk_2`
    FOREIGN KEY (`topic_author`)
    REFERENCES `vzm`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vzm`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vzm`.`replies` (
  `reply_id` INT NOT NULL AUTO_INCREMENT,
  `reply_comment` TEXT NOT NULL,
  `reply_date` DATETIME NOT NULL,
  `reply_author` INT NOT NULL,
  `reply_topic` INT NOT NULL,
  PRIMARY KEY (`reply_id`),
  INDEX `reply_topic` (`reply_topic` ASC) VISIBLE,
  INDEX `reply_author` (`reply_author` ASC) VISIBLE,
  CONSTRAINT `replies_ibfk_1`
    FOREIGN KEY (`reply_topic`)
    REFERENCES `vzm`.`topics` (`topic_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `replies_ibfk_2`
    FOREIGN KEY (`reply_author`)
    REFERENCES `vzm`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
